### PR TITLE
Vedant dev

### PR DESCRIPTION
**Pull request by thiago-roque07**

### CODE REVIEW

**Comment by VedantKalbag** [comment]
Let's merge this back into main once we have something running? Right now its a bunch of unfinished code @thiago-roque07

**Comment by thiago-roque07** [comment]
sure, I'm almost getting to make the juce dsp module to work on it.
Should I create a new branch for what I'm doing, or can I commit in your branch and merge with your stuff?

**Comment by VedantKalbag** [comment]
I think it should be good to commit back into this branch if there isn't any conflict with what I'm working on!

**Comment by VedantKalbag** [comment]
Hey @thiago-roque07 I have finished up the static waveshapers, and the project builds, and works as intended. Should I go ahead and merge back into main?

**Comment by VedantKalbag** [comment]
Merging this back into main as discussed

**Pull request merged**
